### ISSUE TITLE
Bug: App crash on taking photo

### ISSUE THREAD

**Issue by marcauberer** [akshay2211/PixImagePicker#144]
Hi, I want to report a bug, which occurs since the version 1.5.4 of your library. I get following error after taking a photo:

```
2020-10-03 02:12:57.321 16739-16739/com.mrgames13.jimdo.colorconverter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mrgames13.jimdo.colorconverter, PID: 16739
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at com.fxn.pix.Pix$8$1.onFileReady(Pix.java:456)
        at com.otaliastudios.cameraview.CameraUtils$1$1.run(CameraUtils.java:124)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Tested with Pixel 3a phone with Android 11

**Comment by annadnair07** [comment]
Add android:requestLegacyExternalStorage="true" in application manifest.

**Comment by marcauberer** [comment]
Already added. Does not help

**Comment by marcauberer** [comment]
Any suggestions?

**Comment by marcauberer** [comment]
The problem was that my app is targeting API level 30, which means, that it has to implement the scoped storage API. As this library does not support scoped storage yet, I had to downgrade to target API level 29.
@akshay2211 Hope the support for scoped storage will be implemented by you.

**Comment by marcauberer** [comment]
This issue should definetly be fixed! It is app-breaking.

**Comment by marcauberer** [comment]
Hello?

**Comment by akshay2211** [comment]
@marcauberer will reopen and resolve this issue in coming week.

**Comment by marcauberer** [comment]
?

**Comment by akshay2211** [comment]
Hello @marcauberer 
This issue is been resolved in the latest [PixImagePicker version 1.5.5](https://github.com/akshay2211/PixImagePicker#download)

**Comment by marcauberer** [comment]
Hi @akshay2211. I tried it out and cannot confirm it. The bug is still there.

**Comment by akshay2211** [comment]
I have tested the latest release it was working fine in both version 30 and below,
can you kindly recheck it with `implementation  'com.fxn769:pix:1.5.5'`

**Comment by marcauberer** [comment]
Nevermind. The error message is another one than before:
```
2021-01-29 16:04:03.522 30284-30399/com.mrgames13.jimdo.colorconverter E/CameraUtils: writeToFile: could not write file. java.io.FileNotFoundException: /storage/emulated/0/Pix/Camera/IMG_20210129_160450.jpg: open failed: EPERM (Operation not permitted)
    java.io.FileNotFoundException: /storage/emulated/0/Pix/Camera/IMG_20210129_160450.jpg: open failed: EPERM (Operation not permitted)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at com.otaliastudios.cameraview.CameraUtils.writeToFile(CameraUtils.java:92)
        at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:121)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
        at com.otaliastudios.cameraview.CameraUtils.writeToFile(CameraUtils.java:92) 
        at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:121) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by marcauberer** [comment]
I've tested it with the fork of @akshaaatt and it works fine. The reason for that could be to replace `Environment.getExternalStorageDirectory()` with `getExternalFilesDir()`

**Comment by akshaaatt** [comment]
The unknown savior (me XD) has finally arrived!

**Comment by akshaaatt** [comment]
@akshay2211 you could have just checked and merged the pull request that I made. Nevermind I do have a library of my own as well in case @marcauberer you want to check it out. It functions a bit differently. Check it out at https://github.com/akshaaatt/Media-Picker

**Comment by marcauberer** [comment]
Looks promising @akshaaatt ;). Will test it ...

**Comment by akshay2211** [comment]
@marcauberer can you try the pix sample as well, because I'm trying that only and haven't got any issue in it yet.

**Comment by marcauberer** [comment]
@akshay2211 The demo app is also not working. As mentioned above, I use Android 11 on a Google Pixel 3a

**Comment by akshay2211** [comment]
yes got the issue, and pushed the updated code.
thanks for the help @marcauberer

**Comment by marcauberer** [comment]
Yes. Finally it works ;) Thank you.
Could you just release the fix in a new version?

**Comment by akshay2211** [comment]
yes releasing it in few minutes

**Comment by marcauberer** [comment]
Thank you!

**Comment by iadcialim** [comment]
Bumped into the same issue "open failed: EPERM (Operation not permitted)".
Verified v1.5.6 works for me. (pixel2 XL, Android 11)
Thanks @akshay2211
