### ISSUE TITLE
Camera freezes after opening gallery 

### ISSUE THREAD

**Issue by praslnx8** [akshay2211/PixImagePicker#23]
The camera is stuck after swiping up the gallery in Motorolo G4 Naughat device.

Using it in the app https://play.google.com/store/apps/details?id=com.prasilabs.status

**Comment by sabieber** [comment]
Seems to be an Issue resulting from switching to Fotoapparat library

**Comment by AhmMhd** [comment]
@praslnx8 @sabieber @akshay2211 
i am facing the same problem.
Any solutions yet?

**Comment by akshay2211** [comment]
@praslnx8 @AhmMhd 
this issue is been fixed in the latest build [1.2.3](https://github.com/akshay2211/PixImagePicker#download)

**Comment by iv47** [comment]
This issue still occurs. Only way it doesn't happen is if you switch cameras (front to back, vice versa), otherwise it happens every time.

**Steps to reproduce**
*1. Launch camera with ` Pix.start(Context, RequestCode);`
2. Swipe up to show more pics
3. Go back to camera view by swiping down or tapping the back arrow or hardware back
4. Camera view is stuck. *

Same thing happens for Rear or Front Camera

Please note that if camera freezes and you switch from front to back (or vice versa), camera doesn't get stuck when you swipe up to see more pics and go back. 

**So this issue happens if you don't switch cameras**

**Comment by akshay2211** [comment]
Hello @iv47, Kindly look into the version [1.2.4](https://github.com/akshay2211/PixImagePicker#download)
I have resolved it and tested it on MI note 5 pro and Samsung J2.

**Comment by iv47** [comment]
@akshay2211  Just bumped up my project version to `1.2.4` and tested and this issue has been resolved.

Good job man!

**Comment by akshay2211** [comment]
Thanks, @iv47.
I'll be close this thread now @praslnx8 @sabieber @AhmMhd  kindly refer version **[1.2.4](https://github.com/akshay2211/PixImagePicker#download)**.
